"""DEX2C compiler — high-level driver for Phase 4.2.

Orchestrates:
  1. Parse DEX → find target methods
  2. Translate Dalvik bytecode → C/JNI via translator
  3. Generate complete .c source file (translated funcs + registration table)
  4. Compile with NDK (cmake) for each ABI → libagpjnix.so
  5. Patch DEX methods to ACC_NATIVE via dex_writer
"""
from __future__ import annotations

import os
import shutil
import struct
import subprocess
import tempfile
import uuid
from dataclasses import dataclass, field
from pathlib import Path

import sys

# Ensure sibling packer modules are importable.
_packer_dir = str(Path(__file__).resolve().parent.parent)
if _packer_dir not in sys.path:
    sys.path.insert(0, _packer_dir)

from dex_parser import (
    DexFile, EncodedMethod, parse_dex,
    compute_dex_checksum, compute_dex_signature,
)
from dex_writer import patch_methods_to_native
from dex2c.translator import translate_method, D2CMethod, D2CResult, method_d2c_eligibility


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_encoded_method(dex: DexFile, method_idx: int) -> EncodedMethod | None:
    for cd in dex.class_defs:
        if cd.class_data is None:
            continue
        for em in cd.class_data.direct_methods + cd.class_data.virtual_methods:
            if em.method_idx == method_idx:
                return em
    return None


def _iter_class_methods(dex: DexFile, class_desc: str) -> list[EncodedMethod]:
    """Return all methods defined on a class (direct + virtual)."""
    out: list[EncodedMethod] = []
    for cd in dex.class_defs:
        if dex.type_name(cd.class_idx) != class_desc:
            continue
        if cd.class_data is None:
            continue
        out.extend(cd.class_data.direct_methods)
        out.extend(cd.class_data.virtual_methods)
    return out


def _desc_to_jni_slash(desc: str) -> str:
    """``Lcom/example/Foo;`` → ``com/example/Foo``."""
    if desc.startswith("L") and desc.endswith(";"):
        return desc[1:-1]
    return desc


def _c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


# ---------------------------------------------------------------------------
# C source generation
# ---------------------------------------------------------------------------

_C_HEADER = """\
/* AUTO-GENERATED by Enko DEX2C compiler — do not edit. */
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>

typedef uint32_t juint;
typedef uint64_t julong;

/* ---- Cached payload ClassLoader for class resolution fallback ---- */
static jobject     g_d2c_loader      = NULL;
static jmethodID   g_d2c_loadClassM  = NULL;

/* Try FindClass first; fall back to ClassLoader.loadClass(). */
static jclass d2c_find_class(JNIEnv *env, const char *slash_name) {
    jclass clz = (*env)->FindClass(env, slash_name);
    if (clz) return clz;
    /* FindClass failed — clear pending exception. */
    if ((*env)->ExceptionCheck(env)) (*env)->ExceptionClear(env);
    if (!g_d2c_loader || !g_d2c_loadClassM) return NULL;
    /* Convert slash form to dot form for loadClass. */
    size_t len = strlen(slash_name);
    char *dot = (char *)malloc(len + 1);
    if (!dot) return NULL;
    for (size_t i = 0; i < len; i++)
        dot[i] = (slash_name[i] == '/') ? '.' : slash_name[i];
    dot[len] = '\\0';
    jstring jn = (*env)->NewStringUTF(env, dot);
    free(dot);
    if (!jn) return NULL;
    jclass r = (jclass)(*env)->CallObjectMethod(env, g_d2c_loader, g_d2c_loadClassM, jn);
    (*env)->DeleteLocalRef(env, jn);
    if ((*env)->ExceptionCheck(env)) {
        (*env)->ExceptionClear(env);
        return NULL;
    }
    return r;
}

/* ---- Translated method bodies ---- */

"""

_C_REG_STRUCT = """\

/* ---- Registration table ---- */

typedef struct {
    const char *class_desc;   /* e.g. "com/example/Foo" (slash form) */
    const char *method_name;
    const char *signature;    /* JNI signature e.g. "(II)V" */
    int         is_static;
    void       *func_ptr;
} d2c_entry_t;

"""


def generate_c_source(methods: list[D2CMethod]) -> str:
    """Generate a complete .c file from translated methods."""
    parts: list[str] = [_C_HEADER]

    # Emit each translated function body.
    for m in methods:
        parts.append(m.c_body)
        parts.append("\n\n")

    # Emit registration struct and table.
    parts.append(_C_REG_STRUCT)

    parts.append(f"static const d2c_entry_t g_d2c_table[] = {{\n")
    for m in methods:
        cls = _c_escape(_desc_to_jni_slash(m.class_desc))
        name = _c_escape(m.method_name)
        sig = _c_escape(m.jni_sig)
        static_flag = 1 if m.is_static else 0
        parts.append(
            f'    {{"{cls}", "{name}", "{sig}", {static_flag}, (void *){m.func_name}}},\n'
        )
    parts.append("};\n\n")

    parts.append(f"static const int g_d2c_count = {len(methods)};\n\n")

    # Emit the registration entry-point function.
    parts.append(_REGISTRATION_FUNC)

    return "".join(parts)


_REGISTRATION_FUNC = """\
/* ---- Entry point called from libagpcore.so via dlsym ---- */

__attribute__((visibility("default")))
int enko_d2c_init(JNIEnv *env, jobject classLoader) {
    if (!env || !classLoader) return -1;

    /* Get ClassLoader.loadClass(String) method. */
    jclass loaderClz = (*env)->GetObjectClass(env, classLoader);
    if (!loaderClz) return -1;
    jmethodID loadClassM = (*env)->GetMethodID(
        env, loaderClz, "loadClass",
        "(Ljava/lang/String;)Ljava/lang/Class;");
    (*env)->DeleteLocalRef(env, loaderClz);
    if (!loadClassM) return -1;

    /* Cache for d2c_find_class() fallback. */
    g_d2c_loader     = (*env)->NewGlobalRef(env, classLoader);
    g_d2c_loadClassM = loadClassM;

    int registered = 0;

    for (int i = 0; i < g_d2c_count; i++) {
        const d2c_entry_t *e = &g_d2c_table[i];

        /* Convert slash class name to dot form for ClassLoader.loadClass. */
        size_t len = strlen(e->class_desc);
        char *dotName = (char *)malloc(len + 1);
        if (!dotName) continue;
        for (size_t j = 0; j < len; j++) {
            dotName[j] = (e->class_desc[j] == '/') ? '.' : e->class_desc[j];
        }
        dotName[len] = '\\0';

        jstring jName = (*env)->NewStringUTF(env, dotName);
        free(dotName);
        if (!jName) continue;

        jclass targetClz = (jclass)(*env)->CallObjectMethod(
            env, classLoader, loadClassM, jName);
        (*env)->DeleteLocalRef(env, jName);

        if ((*env)->ExceptionCheck(env)) {
            (*env)->ExceptionClear(env);
            continue;
        }
        if (!targetClz) continue;

        JNINativeMethod nm;
        nm.name = (char *)e->method_name;
        nm.signature = (char *)e->signature;
        nm.fnPtr = e->func_ptr;

        jint rc = (*env)->RegisterNatives(env, targetClz, &nm, 1);
        (*env)->DeleteLocalRef(env, targetClz);

        if (rc == 0) {
            registered++;
        } else {
            if ((*env)->ExceptionCheck(env)) {
                (*env)->ExceptionClear(env);
            }
        }
    }

    return registered;
}
"""


# ---------------------------------------------------------------------------
# CMake template for NDK / Hikari compilation
# ---------------------------------------------------------------------------

DEFAULT_OLLVM_CLANG = os.environ.get(
    "ENKO_OLLVM_CLANG",
    "/opt/enko/toolchains/hikari-llvm19/install/bin/clang",
)


_CMAKE_TEMPLATE = """\
cmake_minimum_required(VERSION 3.22)
project(agpjnix C)

option(ENKO_D2C_OLLVM "Enable Hikari/OLLVM obfuscation for libagpjnix.so" OFF)
option(ENKO_D2C_OLLVM_REQUIRED "Fail configure when DEX2C OLLVM is requested but unavailable" OFF)
set(ENKO_D2C_OLLVM_CLANG "__DEFAULT_OLLVM_CLANG__" CACHE FILEPATH "Path to Hikari/OLLVM clang")

if(ENKO_D2C_OLLVM)
    if(NOT EXISTS "${ENKO_D2C_OLLVM_CLANG}")
        if(ENKO_D2C_OLLVM_REQUIRED)
            message(FATAL_ERROR "[enko] DEX2C Hikari/OLLVM clang not found: ${ENKO_D2C_OLLVM_CLANG}")
        endif()
        message(WARNING "[enko] DEX2C Hikari/OLLVM clang not found: ${ENKO_D2C_OLLVM_CLANG}; falling back to normal NDK compile")
        set(ENKO_D2C_OLLVM OFF)
    endif()
endif()

if(ENKO_D2C_OLLVM)
    set(D2C_OLLVM_OBJ "${CMAKE_CURRENT_BINARY_DIR}/ollvm_enko_dex2c.o")
    set(D2C_OLLVM_CFLAGS
        --target=${CMAKE_C_COMPILER_TARGET}
        --sysroot=${CMAKE_SYSROOT}
        -O2 -fPIC
        -DANDROID -DNDEBUG -Dagpjnix_EXPORTS
        -Wall
        -fstack-protector-strong
        -D_FORTIFY_SOURCE=2
        -fno-strict-aliasing
        -fvisibility=hidden
        -ffunction-sections -fdata-sections
        -mllvm -hikari
        -mllvm -enable-cffobf
        -mllvm -enable-subobf
        -mllvm -enable-bcfobf
        -mllvm -enable-splitobf
        -mllvm -enable-strcry
    )

    add_custom_command(
        OUTPUT "${D2C_OLLVM_OBJ}"
        COMMAND ${ENKO_D2C_OLLVM_CLANG} ${D2C_OLLVM_CFLAGS}
            -I${CMAKE_CURRENT_SOURCE_DIR}
            -c "${CMAKE_CURRENT_SOURCE_DIR}/enko_dex2c.c"
            -o "${D2C_OLLVM_OBJ}"
        DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/enko_dex2c.c"
        COMMENT "[enko] Hikari obfuscate DEX2C: enko_dex2c.c"
    )
    add_custom_target(d2c_ollvm_obj DEPENDS "${D2C_OLLVM_OBJ}")
    set_source_files_properties("${D2C_OLLVM_OBJ}" PROPERTIES EXTERNAL_OBJECT TRUE GENERATED TRUE)
    add_library(agpjnix SHARED "${D2C_OLLVM_OBJ}")
    add_dependencies(agpjnix d2c_ollvm_obj)
    set_target_properties(agpjnix PROPERTIES LINKER_LANGUAGE C)
    message(STATUS "[enko] DEX2C Hikari enabled for libagpjnix.so")
else()
    add_library(agpjnix SHARED enko_dex2c.c)
    set_target_properties(agpjnix PROPERTIES LINKER_LANGUAGE C)
    target_compile_options(agpjnix PRIVATE
        -Wall -O2
        -fstack-protector-strong
        -D_FORTIFY_SOURCE=2
        -fno-strict-aliasing
        -fvisibility=hidden
        -ffunction-sections -fdata-sections
    )
endif()

# Make enko_d2c_init visible (it has explicit visibility("default")).
target_link_options(agpjnix PRIVATE
    -Wl,--gc-sections
    -Wl,-z,relro
    -Wl,-z,now
    -Wl,-z,noexecstack
)

find_library(log-lib log)
target_link_libraries(agpjnix ${log-lib})
""".replace("__DEFAULT_OLLVM_CLANG__", DEFAULT_OLLVM_CLANG.replace("\\", "/"))


# ---------------------------------------------------------------------------
# NDK compilation
# ---------------------------------------------------------------------------

# Default ABIs to build for.
DEFAULT_ABIS = ["arm64-v8a", "armeabi-v7a", "x86", "x86_64"]


def _iter_sdk_roots() -> list[Path]:
    roots: list[Path] = []
    for value in (
        os.environ.get("ANDROID_SDK_ROOT", ""),
        os.environ.get("ANDROID_HOME", ""),
        r"D:\Env\tool\Android-Sdk",
        r"D:\Android\Sdk",
        str(Path.home() / "AppData" / "Local" / "Android" / "Sdk"),
    ):
        if not value:
            continue
        path = Path(value).expanduser()
        if path.exists() and path not in roots:
            roots.append(path)
    return roots


def _find_cmake_from_ndk(ndk_path: str) -> str:
    """Locate cmake from NDK, Android SDK, or PATH."""
    ndk = Path(ndk_path)
    # NDK bundles cmake under <ndk>/cmake/<version>/bin/cmake(.exe)
    cmake_dir = ndk / "cmake"
    if cmake_dir.is_dir():
        for ver_dir in sorted(cmake_dir.iterdir(), reverse=True):
            for name in ("cmake.exe", "cmake"):
                candidate = ver_dir / "bin" / name
                if candidate.is_file():
                    return str(candidate)
    # Newer setups often install CMake under Android SDK instead of inside NDK.
    for sdk_root in _iter_sdk_roots():
        sdk_cmake_dir = sdk_root / "cmake"
        if not sdk_cmake_dir.is_dir():
            continue
        for ver_dir in sorted(sdk_cmake_dir.iterdir(), reverse=True):
            for name in ("cmake.exe", "cmake"):
                candidate = ver_dir / "bin" / name
                if candidate.is_file():
                    return str(candidate)
    # Fallback: system cmake
    found = shutil.which("cmake")
    if found:
        return found
    raise RuntimeError("cmake not found in NDK, Android SDK, or PATH")


def _find_ninja_for_cmake(cmake_bin: str) -> str | None:
    cmake_path = Path(cmake_bin).resolve()
    for name in ("ninja.exe", "ninja"):
        sibling = cmake_path.parent / name
        if sibling.is_file():
            return str(sibling)
    found = shutil.which("ninja")
    if found:
        return found
    return None


def _find_toolchain_file(ndk_path: str) -> str:
    tc = Path(ndk_path) / "build" / "cmake" / "android.toolchain.cmake"
    if not tc.is_file():
        raise RuntimeError(f"NDK toolchain file not found: {tc}")
    return str(tc)


def _extract_error_excerpt(output: str, context_after: int = 2) -> str:
    lines = output.splitlines()
    for idx, line in enumerate(lines):
        lowered = line.lower()
        if " error:" in lowered or lowered.startswith("error:") or "fatal error:" in lowered:
            end = min(len(lines), idx + 1 + context_after)
            return "\n".join(lines[idx:end])
    return ""


def _preserve_failed_build(build_root: str, abi: str, phase: str, output: str) -> str:
    dest = Path(tempfile.gettempdir()) / f"enko_d2c_failed_{uuid.uuid4().hex[:8]}"
    shutil.copytree(build_root, dest, dirs_exist_ok=True)
    summary = dest / "failure_summary.txt"
    summary.write_text(
        f"phase: {phase}\nabi: {abi}\n\n{output}",
        encoding="utf-8",
    )
    return str(dest)


def compile_with_ndk(
    c_source: str,
    ndk_path: str,
    output_dir: Path,
    abis: list[str] | None = None,
    ollvm_enabled: bool = True,
    ollvm_clang: str | None = None,
    ollvm_required: bool = False,
    build_report: dict[str, object] | None = None,
) -> dict[str, Path]:
    """Compile the generated C source into libagpjnix.so for each ABI.

    Returns a dict of ``{abi: path_to_so}``.
    """
    if abis is None:
        abis = list(DEFAULT_ABIS)

    cmake_bin = _find_cmake_from_ndk(ndk_path)
    ninja_bin = _find_ninja_for_cmake(cmake_bin)
    toolchain = _find_toolchain_file(ndk_path)
    ollvm_clang = (ollvm_clang or DEFAULT_OLLVM_CLANG).strip()
    ollvm_clang_available = bool(ollvm_clang and Path(ollvm_clang).is_file())

    results: dict[str, Path] = {}
    if build_report is not None:
        build_report.update(
            {
                "requested": bool(ollvm_enabled),
                "required": bool(ollvm_required),
                "clang": ollvm_clang,
                "clang_exists": ollvm_clang_available,
                "per_abi": [],
                "ollvm_protected_libraries": [],
                "ollvm_protected_abis": [],
                "fallback_libraries": [],
                "fallback_abis": [],
                "fallback_used": False,
            }
        )
    build_env = os.environ.copy()
    if ninja_bin:
        build_env["PATH"] = str(Path(ninja_bin).parent) + os.pathsep + build_env.get("PATH", "")
    preserved_failure_dir: str | None = None
    if ollvm_enabled:
        mode = "required" if ollvm_required else "best-effort"
        print(f"[d2c] Hikari/OLLVM requested for libagpjnix.so ({mode}): {ollvm_clang}")
        if not ollvm_clang_available and not ollvm_required:
            print("[!] d2c Hikari/OLLVM clang missing before configure; using normal NDK compile")

    with tempfile.TemporaryDirectory(prefix="enko_d2c_build_") as build_root:
        src_dir = Path(build_root) / "src"
        src_dir.mkdir()
        (src_dir / "enko_dex2c.c").write_text(c_source, encoding="utf-8")
        (src_dir / "CMakeLists.txt").write_text(_CMAKE_TEMPLATE, encoding="utf-8")

        for abi in abis:
            attempts = [True] if ollvm_enabled and (ollvm_clang_available or ollvm_required) else [False]
            if ollvm_enabled and not ollvm_required and ollvm_clang_available:
                attempts.append(False)
            abi_built = False

            for use_ollvm in attempts:
                suffix = "ollvm" if use_ollvm else "ndk"
                build_dir = Path(build_root) / f"build_{abi}_{suffix}"
                build_dir.mkdir()

                # Configure.
                configure_cmd = [
                    cmake_bin,
                    "-GNinja",
                    f"-DCMAKE_TOOLCHAIN_FILE={toolchain}",
                    f"-DANDROID_ABI={abi}",
                    "-DANDROID_PLATFORM=android-26",
                    "-DCMAKE_BUILD_TYPE=Release",
                    f"-DENKO_D2C_OLLVM={'ON' if use_ollvm else 'OFF'}",
                    f"-DENKO_D2C_OLLVM_REQUIRED={'ON' if ollvm_required else 'OFF'}",
                    f"-DENKO_D2C_OLLVM_CLANG={ollvm_clang}",
                    f"-B{build_dir}",
                    f"-S{src_dir}",
                ]
                if ninja_bin:
                    configure_cmd.append(f"-DCMAKE_MAKE_PROGRAM={ninja_bin}")
                print(f"[d2c] cmake configure {abi} ({suffix})")
                r = subprocess.run(
                    configure_cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                    env=build_env,
                )
                if r.returncode != 0:
                    print(f"[!] d2c cmake configure failed for {abi} ({suffix}):\n{r.stdout}")
                    excerpt = _extract_error_excerpt(r.stdout)
                    if excerpt:
                        print(f"[!] d2c first configure error for {abi} ({suffix}):\n{excerpt}")
                    if use_ollvm and not ollvm_required:
                        print(f"[!] d2c Hikari configure failed for {abi}; retrying normal NDK compile")
                        continue
                    if preserved_failure_dir is None:
                        preserved_failure_dir = _preserve_failed_build(
                            build_root, abi, f"configure-{suffix}", r.stdout
                        )
                        print(f"[!] d2c preserved failed build tree: {preserved_failure_dir}")
                    continue

                # Build.
                build_cmd = [cmake_bin, "--build", str(build_dir), "--config", "Release"]
                print(f"[d2c] cmake build {abi} ({suffix})")
                r = subprocess.run(
                    build_cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                    env=build_env,
                )
                if r.returncode != 0:
                    print(f"[!] d2c cmake build failed for {abi} ({suffix}):\n{r.stdout}")
                    excerpt = _extract_error_excerpt(r.stdout)
                    if excerpt:
                        print(f"[!] d2c first build error for {abi} ({suffix}):\n{excerpt}")
                    if use_ollvm and not ollvm_required:
                        print(f"[!] d2c Hikari build failed for {abi}; retrying normal NDK compile")
                        continue
                    if preserved_failure_dir is None:
                        preserved_failure_dir = _preserve_failed_build(
                            build_root, abi, f"build-{suffix}", r.stdout
                        )
                        print(f"[!] d2c preserved failed build tree: {preserved_failure_dir}")
                    continue

                # Find the output .so.
                so_candidates = list(Path(build_dir).rglob("libagpjnix.so"))
                if not so_candidates:
                    print(f"[!] d2c: libagpjnix.so not found after build for {abi} ({suffix})")
                    if use_ollvm and not ollvm_required:
                        print(f"[!] d2c Hikari output missing for {abi}; retrying normal NDK compile")
                        continue
                    continue

                # Copy to output_dir/lib/<abi>/.
                dest_dir = output_dir / "lib" / abi
                dest_dir.mkdir(parents=True, exist_ok=True)
                dest = dest_dir / "libagpjnix.so"
                shutil.copy2(str(so_candidates[0]), str(dest))
                results[abi] = dest
                print(f"[d2c] built {abi} ({suffix}): {dest}")
                if build_report is not None:
                    item = {
                        "abi": abi,
                        "library": "libagpjnix.so",
                        "path": str(dest),
                        "mode": "ollvm" if use_ollvm else "ndk",
                        "ollvm_protected": bool(use_ollvm),
                    }
                    cast_per_abi = build_report.setdefault("per_abi", [])
                    if isinstance(cast_per_abi, list):
                        cast_per_abi.append(item)
                    lib_path = f"lib/{abi}/libagpjnix.so"
                    key = "ollvm_protected_libraries" if use_ollvm else "fallback_libraries"
                    abi_key = "ollvm_protected_abis" if use_ollvm else "fallback_abis"
                    libs = build_report.setdefault(key, [])
                    abi_list = build_report.setdefault(abi_key, [])
                    if isinstance(libs, list) and lib_path not in libs:
                        libs.append(lib_path)
                    if isinstance(abi_list, list) and abi not in abi_list:
                        abi_list.append(abi)
                    if not use_ollvm and ollvm_enabled:
                        build_report["fallback_used"] = True
                abi_built = True
                break

            if not abi_built:
                print(f"[!] d2c: no libagpjnix.so produced for {abi}")

    return results


# ---------------------------------------------------------------------------
# High-level API for harden_apk.py
# ---------------------------------------------------------------------------

def run_dex2c_compilation(
    dex_files: list[Path],
    targets: list[tuple[str, str, str | None]],
    ndk_path: str,
    decoded_apk_dir: Path,
    fail_open: bool = False,
    wipe_insns: bool = True,
    target_abis: list[str] | None = None,
    ollvm_enabled: bool = True,
    ollvm_clang: str | None = None,
    ollvm_required: bool = False,
    build_report: dict[str, object] | None = None,
) -> tuple[int, int]:
    """Translate target methods to C, compile to .so, patch DEX.

    Returns ``(compiled_count, so_count)``.
    """
    if not targets:
        return 0, 0

    ndk_path = (ndk_path or "").strip()
    if not ndk_path:
        msg = "--ndk-path is required for DEX2C compilation"
        if fail_open:
            print(f"[!] {msg}")
            return 0, 0
        raise RuntimeError(msg)

    if not Path(ndk_path).is_dir():
        msg = f"NDK path does not exist: {ndk_path}"
        if fail_open:
            print(f"[!] {msg}")
            return 0, 0
        raise RuntimeError(msg)

    # ── Parse DEX files ──
    parsed: list[DexFile] = []
    for dex_path in dex_files:
        parsed.append(parse_dex(dex_path.read_bytes()))

    # ── Translate target methods ──
    translated: list[D2CMethod] = []
    compiled_indices: dict[int, list[int]] = {}  # dex_idx → [method_idx, ...]
    compiled_set: set[tuple[int, int]] = set()  # (dex_idx, method_idx)
    d2c_skipped_by_reason: dict[str, int] = {}

    for class_desc, method_name, sig in targets:
        matched = False

        for dex_idx, dex in enumerate(parsed):
            candidates: list[EncodedMethod] = []

            # Wildcard: translate all methods in the class.
            if method_name == "*":
                candidates = _iter_class_methods(dex, class_desc)
                if not candidates:
                    continue
                matched = True

            # No signature provided: translate all overloads of method_name in the class.
            elif sig is None:
                ems = _iter_class_methods(dex, class_desc)
                if not ems:
                    continue
                candidates = [
                    em for em in ems
                    if dex.method_name(em.method_idx) == method_name
                ]
                if not candidates:
                    continue
                matched = True

            # Exact match.
            else:
                midx = dex.find_method(class_desc, method_name, sig)
                if midx is None:
                    continue
                matched = True

                em = _find_encoded_method(dex, midx)
                if em is None or em.code is None:
                    msg = f"d2c: no code for {class_desc}->{method_name}{sig}"
                    if fail_open:
                        print(f"[!] {msg}")
                        break
                    raise RuntimeError(msg)

                candidates = [em]

            for em in sorted(candidates, key=lambda x: x.method_idx):
                midx = em.method_idx
                if (dex_idx, midx) in compiled_set:
                    continue

                if em.code is None:
                    msg = f"d2c: no code for {class_desc}->{dex.method_name(midx)}"
                    if method_name == "*" or sig is None:
                        print(f"[!] {msg}; skip")
                        continue
                    if fail_open:
                        print(f"[!] {msg}")
                        continue
                    raise RuntimeError(msg)

                if em.code.insns_size == 0:
                    continue

                eligible, reason = method_d2c_eligibility(em.code)
                if not eligible:
                    # Method uses opcodes DEX2C cannot translate (typically
                    # Kotlin lambda dispatch / invoke-custom). Tally the
                    # reason and skip; the harden orchestrator will see this
                    # method missing from compiled_indices and route it to
                    # VMP or extract instead. Without this pre-check the
                    # translator would raise NotImplementedError partway
                    # through and the method would silently end up
                    # unprotected.
                    d2c_skipped_by_reason[reason] = (
                        d2c_skipped_by_reason.get(reason, 0) + 1
                    )
                    continue

                try:
                    m = translate_method(dex, midx, em)
                    translated.append(m)
                    compiled_indices.setdefault(dex_idx, []).append(midx)
                    compiled_set.add((dex_idx, midx))
                except Exception as exc:
                    msg = (
                        f"d2c: translate failed {class_desc}->{dex.method_name(midx)} "
                        f"(idx={midx}): {exc}"
                    )
                    if fail_open:
                        print(f"[!] {msg}")
                        continue
                    raise RuntimeError(msg) from exc

            break  # first DEX that has it

        if not matched:
            msg = f"d2c: method not found: {class_desc}->{method_name}" + (sig or "")
            if fail_open:
                print(f"[!] {msg}")
            else:
                raise RuntimeError(msg)

    if d2c_skipped_by_reason:
        total_skipped = sum(d2c_skipped_by_reason.values())
        detail = ", ".join(
            f"{reason}={count}" for reason, count in
            sorted(d2c_skipped_by_reason.items(), key=lambda kv: -kv[1])
        )
        print(
            f"[d2c] {total_skipped} method(s) routed away from DEX2C "
            f"due to unsupported Dalvik opcodes ({detail}); "
            f"these should fall back to VMP or method extract."
        )

    if not translated:
        return 0, 0

    print(f"[d2c] translated {len(translated)} method(s)")

    # ── Generate C source ──
    c_source = generate_c_source(translated)

    # ── Detect which ABIs the decoded APK has ──
    compile_abis: list[str] | None = target_abis
    if compile_abis is None:
        lib_root = decoded_apk_dir / "lib"
        if lib_root.is_dir():
            existing = sorted(p.name for p in lib_root.iterdir() if p.is_dir())
            if existing:
                compile_abis = existing

    # ── Compile with NDK ──
    try:
        so_map = compile_with_ndk(
            c_source,
            ndk_path,
            decoded_apk_dir,
            abis=compile_abis,
            ollvm_enabled=ollvm_enabled,
            ollvm_clang=ollvm_clang,
            ollvm_required=ollvm_required,
            build_report=build_report,
        )
    except Exception as exc:
        msg = f"d2c: NDK compilation failed: {exc}"
        if fail_open:
            print(f"[!] {msg}")
            return len(translated), 0
        raise RuntimeError(msg) from exc

    if not so_map:
        msg = "d2c: NDK compilation produced no .so files"
        if fail_open:
            print(f"[!] {msg}")
            return len(translated), 0
        raise RuntimeError(msg)

    # ── Patch DEX: mark compiled methods as ACC_NATIVE ──
    for dex_idx, method_indices in compiled_indices.items():
        dex = parsed[dex_idx]
        patched = patch_methods_to_native(dex, method_indices, wipe_insns=wipe_insns)
        dex_files[dex_idx].write_bytes(patched)
        print(
            f"[d2c] patched {dex_files[dex_idx].name}: "
            f"{len(method_indices)} method(s) → native"
        )

    return len(translated), len(so_map)
